# Generated by Django 3.2.4 on 2021-09-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_like_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(db_index=True, verbose_name='Body'),
        ),
    ]
